In [1]:
import numpy as np

arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np

A = np.array([[1,2], [3,4]])
B = np.array([[1,1], [1,1]])
C = A + B
C

array([[2, 3],
       [4, 5]])

In [6]:
import numpy as np

A = np.array([[1,2], [3,4],[5,6]])
B = np.array([[2,3], [2,3]])
C = np.matmul(A,B)
C

array([[ 6,  9],
       [14, 21],
       [22, 33]])

In [7]:
import numpy as no

A = np.array([[1,2],[3,4]])
k = 10
C = k * A
C

array([[10, 20],
       [30, 40]])