In [6]:
###### from konlpy.tag import Komoran
import numpy as np

komoran = Komoran()
text = "오늘 날씨는 구름이 많아요"

# 명사만 추출 1
nouns = komoran.nouns(text)
print(nouns)

#  단어 사전 구축 및 단어별 인덱스 부여 2
dics = {}
for word in nouns:
    if word not in dics.keys():
        dics[word] = len(dics)           
print(dics)

# 원-핫 인코딩
nb_classes = len(dics) # 원-핫 벡터 차원의 크기를 결정한다.
targets = list(dics.values())#단어별 인덱스값이 필요하기 때문에 딕셔너리의 함수를 이용해 value값만 리스트로 변환
one_hot_targets = np.eye(nb_classes)[targets]#원-핫 백터를 만들기 위해서는 넘파이의 eye() 함수를 이용
                                            #eye() 함수는 단위행렬을 만들어 줍니다.
                                            #eye() 함수의 인자를 크기대로 단위행렬을 반환하며,
                                            #eye() 함수뒤에 붙은 [target]를 이용해 생성된 단위행렬의 순서를 
                                            #단어 사전의 순서에 맞게 정렬
print(one_hot_targets)

['오늘', '날씨', '구름']
{'오늘': 0, '날씨': 1, '구름': 2}
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
